services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG='TRUE'
      - SECRET_KEY='django-insecure-acpb)$ofic3%@d+^v(k9u-nd(1($i2%^6q*s2dc=-_pkudsu90'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/social_feed_db
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_feed_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
